name: abc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0
# // her yayın için 0.1.0+1 arttırılmalı

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animated_icon: ^0.0.4
  http: ^1.0.0
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  google_fonts: ^4.0.3
  intl: ^0.18.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
