name: abc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  animated_icon: ^0.0.4
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
